server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: Online Course Management System API

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8888/realms/management-realm/protocol/openid-connect/certs
          issuer-uri: http://keycloak:8888/realms/management-realm
  flyway:
    enabled: true
    locations: classpath:database/migration
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/coursedb
    username: coursedb_user
    password: coursedb_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
